name: Firebase Functions CI
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm i -g firebase-tools jq

      # Sanity checks
      - name: Sanity - echo project id
        run: |
          echo "FIREBASE_PROJECT_ID (from secret): ${{ secrets.FIREBASE_PROJECT_ID }}"
          test -n "${{ secrets.FIREBASE_PROJECT_ID }}" || (echo "FIREBASE_PROJECT_ID is empty" && exit 1)

      - name: Sanity - write and inspect SA JSON
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > $HOME/sa.json
          node -e "const fs=require('fs');const p=process.env.HOME+'/sa.json';const j=JSON.parse(fs.readFileSync(p,'utf8'));console.log('SA project_id:', j.project_id);console.log('SA client_email:', j.client_email);"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/sa.json" >> $GITHUB_ENV

      - name: Sanity - list accessible projects
        run: firebase projects:list --non-interactive || true

      - name: Set project id from secret
        run: echo '${{ secrets.FIREBASE_PROJECT_ID }}' > project.txt

      - name: Install & build functions
        working-directory: apps/functions
        run: |
          npm install --no-audit --no-fund
          npm run build

      - name: Deploy functions
        run: firebase deploy --only functions --project "$(cat project.txt)" --non-interactive
