name: Firebase Functions CI
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Log into Google Cloud with your deployer SA (GCP_SA_KEY)
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Install Firebase CLI
        run: npm i -g firebase-tools jq

      # (Optional) sanity
      - name: Sanity - who am I / which project
        run: |
          gcloud config list
          gcloud auth list
          gcloud projects describe "${{ secrets.FIREBASE_PROJECT_ID }}" --format="value(projectNumber,projectId)"

      - name: Install & build functions
        working-directory: apps/functions
        run: |
          npm install --no-audit --no-fund
          npm run build

      - name: Deploy functions
        run: firebase deploy --only functions --project "${{ secrets.FIREBASE_PROJECT_ID }}" --non-interactive
