name: Firebase Functions CI
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Authenticate to Google Cloud using your service account JSON
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}

      # Make a Firebase CLI token from gcloud and expose it to subsequent steps
      - name: Export FIREBASE_TOKEN from gcloud
        run: echo "FIREBASE_TOKEN=$(gcloud auth print-access-token)" >> $GITHUB_ENV

      - name: Install Firebase CLI
        run: npm i -g firebase-tools jq

      # Sanity checks (helpful diagnostics)
      - name: Sanity - echo project id
        run: |
          echo "FIREBASE_PROJECT_ID (from secret): ${{ secrets.FIREBASE_PROJECT_ID }}"
          test -n "${{ secrets.FIREBASE_PROJECT_ID }}" || (echo "FIREBASE_PROJECT_ID is empty" && exit 1)

      - name: Sanity - print SA identity
        run: |
          gcloud config list
          gcloud auth list
          gcloud projects describe "${{ secrets.FIREBASE_PROJECT_ID }}" --format="value(projectNumber,projectId)"

      - name: Sanity - firebase can list projects
        run: firebase projects:list --non-interactive || true

      - name: Install & build functions
        working-directory: apps/functions
        run: |
          npm install --no-audit --no-fund
          npm run build

      - name: Deploy functions
        env:
          # Firebase CLI will use this token for auth
          FIREBASE_TOKEN: ${{ env.FIREBASE_TOKEN }}
        run: firebase deploy --only functions --project "${{ secrets.FIREBASE_PROJECT_ID }}" --non-interactive
